### ISSUE TITLE
매수/매도 주문 제출 API 구현

### ISSUE THREAD

**Issue by JangWooJin1** [Pda5th-SolZipMoa/backend#1]
## Description

- **매수 주문**을 제출할 때, 사용자의 보유 자산(돈)을 확인하고, 충분한 금액이 있을 경우 주문을 처리하여 기록을 저장하고 Redis의 호가창을 업데이트
- **매도 주문**을 제출할 때, 사용자의 보유 토큰 수량을 확인하고, 충분한 수량이 있을 경우 주문을 처리하여 기록을 저장하고 Redis의 호가창을 업데이트

## Todo

- [x] 매수 주문 제출 API 구현
  - [x] 사용자의 보유 금액 확인
  - [x] 금액이 충분한 경우 매수 주문 기록 저장
  - [x] Redis에 호가창 데이터 업데이트

![image](https://github.com/user-attachments/assets/90249a8d-496b-4201-9fed-5312fc664c2d)

- [x] 매도 주문 제출 API 구현
  - [x] 사용자의 보유 토큰 수량 확인
  - [x] 수량이 충분한 경우 매도 주문 기록 저장
  - [x] Redis에 호가창 데이터 업데이트

![image](https://github.com/user-attachments/assets/f83b4fe9-affd-4c57-b611-dfbabef870f9)
