### ISSUE TITLE
주문 취소 기능 구현

### ISSUE THREAD

**Issue by JangWooJin1** [Pda5th-SolZipMoa/backend#18]
### Description

주문 취소 기능을 새롭게 구현
**Method**: `DELETE`  
**URL**: `/api/orders/{order_id}`  

### Todo
- [x] **주문 상태 변경**:
   - `Order_Archive` 테이블에서 `order_id`에 해당하는 주문의 상태를 `cancelled`로 변경.

- [x] **주문 복원 로직**:
   - 매수 주문 취소 시, `Users` 테이블의 `orderable_balance`를 복원.
   - 매도 주문 취소 시, `Ownerships` 테이블의 `tradeable_tokens`를 복원.

- [x] **Redis 호가창 업데이트**:
   - 취소된 주문에 해당하는 `price_per_token` 키에서 `order_id`를 삭제.
   - 특정 가격 레벨의 주문 목록이 비어 있으면 해당 레벨을 제거.
