### ISSUE TITLE
사이드 디테일 페이지 백엔드 구현

### ISSUE THREAD

**Issue by ILKYOYANG** [Pda5th-SolZipMoa/backend#29]
## Description

- 사이드 디테일 페이지 백엔드 코드 구현

## Todo

- [x] ChatGPT API 연결
- [x] 백엔드 기반 뉴스 크롤링 및 더보기 연동
- [x] 백엔드 라우팅 기능 추가
