### ISSUE TITLE
상세 페이지 apartment api 구현

### ISSUE THREAD

**Issue by besthong** [Pda5th-SolZipMoa/backend#5]
## Description

- 상세페이지 내 api 구현
- 오픈API "국토교통부_건축HUB_건축물대장정보 서비스" 내 총괄표제부 api 사용 
- 오픈API "국토교통부_아파트 매매 실거래가 상세 자료" 사용하여, 총괄표제부에서 얻은 지번 코드로 해당 아파트의 최근 5개 실거래 데이터 추출(층 구분)

- 기존 실시간 AP요청으로 아파트 실거래 데이터를 가져왔으나 속도 이슈 발생 -> cron으로 매일 실거래 데이터 5개를 가져와 db에 저장 후 db를 보여주는 식으로 변경
```python
{
  "건물정보": {
    "대지면적": "41",
    "건폐율": "1249.11",
    "연면적": "803.123",
    "용적률": "41245.1",
    "건물명": "아크로서울포레스트",
    "주소": "서울 성동구 왕십리로 83-21",
    "이미지URL": [
      "https://newsimg.sedaily.com/2017/03/17/1ODEN68FO5_15.jpg"
    ]
  },
  "최신거래": [
    {
      "아파트명": "아크로서울포레스트",
      "거래금액": "1,100,000",
      "전용면적": "",
      "층": "35",
      "계약연도": "2024",
      "계약월": "7",
      "계약일": "10"
    },
    {
      "아파트명": "아크로서울포레스트",
      "거래금액": "1,450,000",
      "전용면적": "",
      "층": "35",
      "계약연도": "2024",
      "계약월": "7",
      "계약일": "4"
    },
```

## Todo

- [x] 국토교통부_건축HUB_건축물대장정보 서비스 - 총괄표제부 API 검증
- [x] 국토교통부_아파트 매매 실거래가 상세자료 - API 검증
- [x] 하나의 라우팅 내 db조회 (건물 정보) 및 시세 정보 (실시간) 추출
- [x] 건물 정보 데이터 가공, 시세 정보 데이터 가공
- [x] 이미지 처리, 썸네일 처리
- [ ] 생성된 토큰 보여주기
- [x] 속도 개선
