### ISSUE TITLE
메인페이지 API 구현

### ISSUE THREAD

**Issue by yujeongFE** [Pda5th-SolZipMoa/backend#7]
## Description
메인페이지는 사용자에게 현재 위치를 중심으로 건물 목록을 지도와 리스트 형태로 제공하는 화면입니다. 
사용자는 지도를 통해 주변 건물의 위치를 확인하고, 오른쪽 리스트에서 건물의 주요 정보를 확인할 수 있습니다.
 각 건물 카드에는 수익률, 공모 금액, 거래 가능 토큰 수 등의 정보가 포함됩니다.

## Todo

- [x]  메인페이지 건물 리스트 조회 API
- [x] 건물 위치 데이터를 지도에서 표시할 수 있도록 반환하는 API 수정 
- [x] 지도 줌 레벨과 위치 변경에 따라 동적으로 데이터를 갱신
- [x] 수익률, 가격, 거리 등을 기준으로 정렬
